# -*- coding:utf-8 -*-

from datetime import datetime
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from core import constants

class StockStats(db.Model):
    __tablename__ = "stock_stats"
    id = db.Column(db.Integer, primary_key=True)  # 用户编号
    date = db.Column(db.DateTime, nullable=False)  # 用户编号
    code = db.Column(db.String(8), nullable=False)  # 用户编号
    name = db.Column(db.String(32), nullable=False)  # 用户编号
    close = db.Column(db.Float, nullable=False)  # 收盘价
    macd = db.Column(db.Float, nullable=False)
    macds = db.Column(db.Float, nullable=False)
    macdh = db.Column(db.Float, nullable=False)
    kdjk = db.Column(db.Float, nullable=False)
    kdjd = db.Column(db.Float, nullable=False)
    kdjj = db.Column(db.Float, nullable=False)
    boll_ub = db.Column(db.Float, nullable=False)
    boll = db.Column(db.Float, nullable=False)
    boll_lb = db.Column(db.Float, nullable=False)
    trix = db.Column(db.Float, nullable=False)
    trix_20_sma = db.Column(db.Float, nullable=False)
    tema = db.Column(db.Float, nullable=False)
    cr = db.Column(db.Float, nullable=False)
    cr_ma1 = db.Column(db.Float, nullable=False)
    cr_ma2 = db.Column(db.Float, nullable=False)
    cr_ma3 = db.Column(db.Float, nullable=False)
    rsi_6 = db.Column(db.Float, nullable=False)
    rsi_12 = db.Column(db.Float, nullable=False)
    rsi = db.Column(db.Float, nullable=False)
    rsi_24 = db.Column(db.Float, nullable=False)
    vr = db.Column(db.Float, nullable=False)
    vr_6_sma = db.Column(db.Float, nullable=False)
    roc = db.Column(db.Float, nullable=False)
    rocma = db.Column(db.Float, nullable=False)
    rocema = db.Column(db.Float, nullable=False)
    pdi = db.Column(db.Float, nullable=False)
    mdi = db.Column(db.Float, nullable=False)
    dx = db.Column(db.Float, nullable=False)
    adx = db.Column(db.Float, nullable=False)
    adxr = db.Column(db.Float, nullable=False)
    wr_6 = db.Column(db.Float, nullable=False)
    wr_10 = db.Column(db.Float, nullable=False)
    wr_14 = db.Column(db.Float, nullable=False)
    cci = db.Column(db.Float, nullable=False)
    cci_84 = db.Column(db.Float, nullable=False)
    tr = db.Column(db.Float, nullable=False)
    atr = db.Column(db.Float, nullable=False)
    dma = db.Column(db.Float, nullable=False)
    dma_10_sma = db.Column(db.Float, nullable=False)
    obv = db.Column(db.Float, nullable=False)
    sar = db.Column(db.Float, nullable=False)
    psy = db.Column(db.Float, nullable=False)
    psyma = db.Column(db.Float, nullable=False)
    br = db.Column(db.Float, nullable=False)
    ar = db.Column(db.Float, nullable=False)
    emv = db.Column(db.Float, nullable=False)
    emva = db.Column(db.Float, nullable=False)
    bias = db.Column(db.Float, nullable=False)
    mfi = db.Column(db.Float, nullable=False)
    mfisma = db.Column(db.Float, nullable=False)
    vwma = db.Column(db.Float, nullable=False)
    mvwma = db.Column(db.Float, nullable=False)
    ppo = db.Column(db.Float, nullable=False)
    ppos = db.Column(db.Float, nullable=False)
    ppoh = db.Column(db.Float, nullable=False)
    wt1 = db.Column(db.Float, nullable=False)
    wt2 = db.Column(db.Float, nullable=False)
    supertrend_ub = db.Column(db.Float, nullable=False)
    supertrend = db.Column(db.Float, nullable=False)
    supertrend_lb = db.Column(db.Float, nullable=False)
    dpo = db.Column(db.Float, nullable=False)
    madpo = db.Column(db.Float, nullable=False)
    vhf = db.Column(db.Float, nullable=False)
    rvi = db.Column(db.Float, nullable=False)
    rvis = db.Column(db.Float, nullable=False)
    fi = db.Column(db.Float, nullable=False)
    force_2 = db.Column(db.Float, nullable=False)
    force_13 = db.Column(db.Float, nullable=False)
    ene_ue = db.Column(db.Float, nullable=False)
    ene = db.Column(db.Float, nullable=False)
    ene_le = db.Column(db.Float, nullable=False)
    stochrsi_k = db.Column(db.Float, nullable=False)
    stochrsi_d = db.Column(db.Float, nullable=False)
