"""empty message

Revision ID: 04258efe6f9f
Revises: 
Create Date: 2024-05-13 11:12:34.453383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04258efe6f9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('macd', sa.Float(), nullable=False),
    sa.Column('macds', sa.Float(), nullable=False),
    sa.Column('macdh', sa.Float(), nullable=False),
    sa.Column('kdjk', sa.Float(), nullable=False),
    sa.Column('kdjd', sa.Float(), nullable=False),
    sa.Column('kdjj', sa.Float(), nullable=False),
    sa.Column('boll_ub', sa.Float(), nullable=False),
    sa.Column('boll', sa.Float(), nullable=False),
    sa.Column('boll_lb', sa.Float(), nullable=False),
    sa.Column('trix', sa.Float(), nullable=False),
    sa.Column('trix_20_sma', sa.Float(), nullable=False),
    sa.Column('tema', sa.Float(), nullable=False),
    sa.Column('cr', sa.Float(), nullable=False),
    sa.Column('cr_ma1', sa.Float(), nullable=False),
    sa.Column('cr_ma2', sa.Float(), nullable=False),
    sa.Column('cr_ma3', sa.Float(), nullable=False),
    sa.Column('rsi_6', sa.Float(), nullable=False),
    sa.Column('rsi_12', sa.Float(), nullable=False),
    sa.Column('rsi', sa.Float(), nullable=False),
    sa.Column('rsi_24', sa.Float(), nullable=False),
    sa.Column('vr', sa.Float(), nullable=False),
    sa.Column('vr_6_sma', sa.Float(), nullable=False),
    sa.Column('roc', sa.Float(), nullable=False),
    sa.Column('rocma', sa.Float(), nullable=False),
    sa.Column('rocema', sa.Float(), nullable=False),
    sa.Column('pdi', sa.Float(), nullable=False),
    sa.Column('mdi', sa.Float(), nullable=False),
    sa.Column('dx', sa.Float(), nullable=False),
    sa.Column('adx', sa.Float(), nullable=False),
    sa.Column('adxr', sa.Float(), nullable=False),
    sa.Column('wr_6', sa.Float(), nullable=False),
    sa.Column('wr_10', sa.Float(), nullable=False),
    sa.Column('wr_14', sa.Float(), nullable=False),
    sa.Column('cci', sa.Float(), nullable=False),
    sa.Column('cci_84', sa.Float(), nullable=False),
    sa.Column('tr', sa.Float(), nullable=False),
    sa.Column('atr', sa.Float(), nullable=False),
    sa.Column('dma', sa.Float(), nullable=False),
    sa.Column('dma_10_sma', sa.Float(), nullable=False),
    sa.Column('obv', sa.Float(), nullable=False),
    sa.Column('sar', sa.Float(), nullable=False),
    sa.Column('psy', sa.Float(), nullable=False),
    sa.Column('psyma', sa.Float(), nullable=False),
    sa.Column('br', sa.Float(), nullable=False),
    sa.Column('ar', sa.Float(), nullable=False),
    sa.Column('emv', sa.Float(), nullable=False),
    sa.Column('emva', sa.Float(), nullable=False),
    sa.Column('bias', sa.Float(), nullable=False),
    sa.Column('mfi', sa.Float(), nullable=False),
    sa.Column('mfisma', sa.Float(), nullable=False),
    sa.Column('vwma', sa.Float(), nullable=False),
    sa.Column('mvwma', sa.Float(), nullable=False),
    sa.Column('ppo', sa.Float(), nullable=False),
    sa.Column('ppos', sa.Float(), nullable=False),
    sa.Column('ppoh', sa.Float(), nullable=False),
    sa.Column('wt1', sa.Float(), nullable=False),
    sa.Column('wt2', sa.Float(), nullable=False),
    sa.Column('supertrend_ub', sa.Float(), nullable=False),
    sa.Column('supertrend', sa.Float(), nullable=False),
    sa.Column('supertrend_lb', sa.Float(), nullable=False),
    sa.Column('dpo', sa.Float(), nullable=False),
    sa.Column('madpo', sa.Float(), nullable=False),
    sa.Column('vhf', sa.Float(), nullable=False),
    sa.Column('rvi', sa.Float(), nullable=False),
    sa.Column('rvis', sa.Float(), nullable=False),
    sa.Column('fi', sa.Float(), nullable=False),
    sa.Column('force_2', sa.Float(), nullable=False),
    sa.Column('force_13', sa.Float(), nullable=False),
    sa.Column('ene_ue', sa.Float(), nullable=False),
    sa.Column('ene', sa.Float(), nullable=False),
    sa.Column('ene_le', sa.Float(), nullable=False),
    sa.Column('stochrsi_k', sa.Float(), nullable=False),
    sa.Column('stochrsi_d', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_stats')
    # ### end Alembic commands ###
