"""empty message

Revision ID: 243a4d8f20be
Revises: 
Create Date: 2024-05-24 09:35:10.247715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243a4d8f20be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_shareholder',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('price', sa.String(length=50), nullable=False),
    sa.Column('zxzdf', sa.String(length=50), nullable=False),
    sa.Column('zxgdhs', sa.String(length=50), nullable=False),
    sa.Column('zxhjcgsl', sa.String(length=50), nullable=False),
    sa.Column('zxhjcgsz', sa.String(length=50), nullable=False),
    sa.Column('zxhjcgbl', sa.String(length=50), nullable=False),
    sa.Column('declaration_date', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_shareholder')
    # ### end Alembic commands ###
