"""empty message

Revision ID: 261dfdba9d3b
Revises: e2fc97ba6ccf
Create Date: 2024-05-22 15:37:19.204583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261dfdba9d3b'
down_revision = 'e2fc97ba6ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_indicators', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
