"""empty message

Revision ID: 26c7947f37e0
Revises: d234a92418bd
Create Date: 2024-05-22 15:38:59.796895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26c7947f37e0'
down_revision = 'd234a92418bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_indicators', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.VARCHAR(length=8), nullable=False))

    # ### end Alembic commands ###
