"""empty message

Revision ID: 37b155cccd4f
Revises: a57e581fc32d
Create Date: 2024-05-24 15:01:23.125595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37b155cccd4f'
down_revision = 'a57e581fc32d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_shareholder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_code', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('stock_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('price_range', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('shareholder_count', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('shareholder_chigu_shuliang', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('shareholder_chigu_shizhi', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('shareholder_chigu_bili', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gonggao_date', sa.String(length=50), nullable=False))
        batch_op.drop_column('declaration_date')
        batch_op.drop_column('zxhjcgbl')
        batch_op.drop_column('zxhjcgsl')
        batch_op.drop_column('code')
        batch_op.drop_column('zxgdhs')
        batch_op.drop_column('zxzdf')
        batch_op.drop_column('zxhjcgsz')
        batch_op.drop_column('id')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_shareholder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('id', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('zxhjcgsz', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('zxzdf', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('zxgdhs', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('code', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('zxhjcgsl', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('zxhjcgbl', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('declaration_date', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('gonggao_date')
        batch_op.drop_column('shareholder_chigu_bili')
        batch_op.drop_column('shareholder_chigu_shizhi')
        batch_op.drop_column('shareholder_chigu_shuliang')
        batch_op.drop_column('shareholder_count')
        batch_op.drop_column('price_range')
        batch_op.drop_column('stock_name')
        batch_op.drop_column('stock_code')

    # ### end Alembic commands ###
