"""empty message

Revision ID: a4655aeb9b0d
Revises: 243a4d8f20be
Create Date: 2024-05-24 10:45:00.315616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4655aeb9b0d'
down_revision = '243a4d8f20be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_shareholder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_shareholder', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
