"""empty message

Revision ID: a4d42b049a7c
Revises: 04258efe6f9f
Create Date: 2024-05-15 15:05:45.758544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d42b049a7c'
down_revision = '04258efe6f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('f2', sa.Float(), nullable=False),
    sa.Column('f3', sa.Float(), nullable=False),
    sa.Column('f4', sa.Float(), nullable=False),
    sa.Column('f5', sa.Float(), nullable=False),
    sa.Column('f6', sa.Float(), nullable=False),
    sa.Column('f7', sa.Float(), nullable=False),
    sa.Column('f8', sa.Float(), nullable=False),
    sa.Column('f10', sa.Float(), nullable=False),
    sa.Column('f11', sa.Float(), nullable=False),
    sa.Column('f12', sa.Float(), nullable=False),
    sa.Column('f13', sa.Float(), nullable=False),
    sa.Column('f14', sa.Float(), nullable=False),
    sa.Column('f15', sa.Float(), nullable=False),
    sa.Column('f16', sa.Float(), nullable=False),
    sa.Column('f17', sa.Float(), nullable=False),
    sa.Column('f18', sa.Float(), nullable=False),
    sa.Column('f20', sa.Float(), nullable=False),
    sa.Column('f21', sa.Float(), nullable=False),
    sa.Column('f22', sa.Float(), nullable=False),
    sa.Column('f23', sa.Float(), nullable=False),
    sa.Column('f24', sa.Float(), nullable=False),
    sa.Column('f25', sa.Float(), nullable=False),
    sa.Column('f26', sa.Float(), nullable=False),
    sa.Column('f37', sa.Float(), nullable=False),
    sa.Column('f38', sa.Float(), nullable=False),
    sa.Column('f39', sa.Float(), nullable=False),
    sa.Column('f40', sa.Float(), nullable=False),
    sa.Column('f41', sa.Float(), nullable=False),
    sa.Column('f45', sa.Float(), nullable=False),
    sa.Column('f46', sa.Float(), nullable=False),
    sa.Column('f48', sa.Float(), nullable=False),
    sa.Column('f49', sa.Float(), nullable=False),
    sa.Column('f57', sa.Float(), nullable=False),
    sa.Column('f61', sa.Float(), nullable=False),
    sa.Column('f100', sa.Float(), nullable=False),
    sa.Column('f112', sa.Float(), nullable=False),
    sa.Column('f113', sa.Float(), nullable=False),
    sa.Column('f114', sa.Float(), nullable=False),
    sa.Column('f115', sa.Float(), nullable=False),
    sa.Column('f221', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('user', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_roles')
    op.drop_table('stock_info')
    # ### end Alembic commands ###
