"""empty message

Revision ID: a57e581fc32d
Revises: ae112af553b6
Create Date: 2024-05-24 11:15:44.328799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a57e581fc32d'
down_revision = 'ae112af553b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_shareholder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_shareholder', schema=None) as batch_op:
        batch_op.drop_column('info')

    # ### end Alembic commands ###
