"""empty message

Revision ID: ae112af553b6
Revises: a4655aeb9b0d
Create Date: 2024-05-24 10:52:55.936651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae112af553b6'
down_revision = 'a4655aeb9b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_shareholder', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('zxzdf',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('zxgdhs',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('zxhjcgsl',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('zxhjcgsz',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('zxhjcgbl',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_shareholder', schema=None) as batch_op:
        batch_op.alter_column('zxhjcgbl',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('zxhjcgsz',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('zxhjcgsl',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('zxgdhs',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('zxzdf',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
