"""empty message

Revision ID: d234a92418bd
Revises: 261dfdba9d3b
Create Date: 2024-05-22 15:38:40.581487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd234a92418bd'
down_revision = '261dfdba9d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_indicators', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_indicators', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=8),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
