"""empty message

Revision ID: ea82ed08ad2c
Revises: 
Create Date: 2024-05-22 11:29:27.018499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea82ed08ad2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_info', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('f2',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_info', schema=None) as batch_op:
        batch_op.alter_column('f2',
               existing_type=sa.String(length=50),
               type_=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
