"""empty message

Revision ID: fa582cc6f2ed
Revises: 37b155cccd4f
Create Date: 2024-05-24 17:13:45.096893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa582cc6f2ed'
down_revision = '37b155cccd4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_shareholder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.drop_column('stock_code')
        batch_op.drop_column('stock_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_shareholder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('stock_code', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('name')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
